#!/bin/bash

echo " "
echo "Project CLI Utility"
echo " "
echo "Example:"
echo " "
echo "      ./project COMMAND ARGUMENT1 ARGUMENT2 ..."
echo " "
echo "Commands:"
echo " "
echo "      build               Build the project package."
echo "      help                Output help information on the available CLI commands."
echo "      setup               Setup the project after a fresh clone."
echo " "
