#!/bin/bash

echo "➜ Install Composer Dependencies"
cd server && composer install && cd ..

echo "➜ Install NPM Dependencies"
cd client && npm install && cd ..

echo "➜ Listen To Incoming Requests"
php-fpm
